import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");
const escape = (value = "") => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character]);
const readCollection = (name) => readdirSync(path.join(root, "data", name)).filter((file) => file.endsWith(".json")).map((file) => JSON.parse(readFileSync(path.join(root, "data", name, file), "utf8")));
const sortName = (a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" });
const films = readCollection("films").sort((a, b) => (b.year ?? 0) - (a.year ?? 0));
const people = readCollection("people").sort(sortName);
const organisations = readCollection("organisations").sort(sortName);
const places = readCollection("places").sort(sortName);
const themes = readCollection("themes").sort(sortName);
const history = readCollection("history").sort((a, b) => (a.year ?? 9999) - (b.year ?? 9999));
const resources = readCollection("resources").sort((a, b) => a.title.localeCompare(b.title, "en", { sensitivity: "base" }));
const byId = (items) => new Map(items.map((item) => [item.id, item]));
const peopleMap = byId(people), filmsMap = byId(films), placesMap = byId(places), themesMap = byId(themes), historyMap = byId(history);
const featuredFilmIds = ["tabataba", "mahaleo", "ady-gasy", "fahavalo-madagascar-1947", "disco-afrika", "malagasy-mankany"];
const featuredFilms = featuredFilmIds.map((id) => filmsMap.get(id)).filter(Boolean);
const featuredPeople = people.filter((person) => !person.archival).slice(0, 6);
const roles = [...new Set(people.flatMap((person) => person.roles ?? []))].sort();

function layout({ title, description, body, current = "" }) {
  const pageTitle = title ? `${escape(title)} — Filmada` : "Filmada — Malagasy film and audiovisual directory";
  const nav = (key, href, label, emphasis = false) => `<a class="${emphasis ? "nav-emphasis" : ""}" ${current === key ? 'aria-current="page"' : ""} href="${href}">${label}</a>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${pageTitle}</title><meta name="description" content="${escape(description)}"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip" href="#content">Skip to content</a><header class="site-header"><nav class="nav shell" aria-label="Main navigation"><a class="brand" href="/"><span></span>Filmada</a><button class="menu" aria-expanded="false" aria-controls="navlinks">Menu</button><div id="navlinks" class="navlinks">${nav("directory", "/directory/", "Directory")}${nav("people", "/people/", "People", true)}${nav("films", "/films/", "Films", true)}${nav("opportunities", "/opportunities/", "Opportunities")}${nav("history", "/history/", "History")}<a href="/contribute/">Contribute</a></div></nav></header><main id="content">${body}</main><footer><div class="shell footer"><div><a class="brand" href="/"><span></span>Filmada</a><p>An open, collaborative directory of Madagascar's film and audiovisual field—built carefully, one verified fragment at a time.</p></div><div><a href="/directory/">Directory</a><a href="/about/">About</a><a href="/contribute/">Contribute</a><a href="https://github.com/mosenjo/filmada">Source on GitHub</a></div></div></footer><script src="/site.js"></script></body></html>`;
}

function write(route, html) {
  const directory = path.join(dist, route);
  mkdirSync(directory, { recursive: true });
  writeFileSync(path.join(directory, "index.html"), html);
}

const statusBadge = (record) => record.archival ? '<span class="status archival">Archival record · needs confirmation</span>' : record.status === "verified" ? '<span class="status verified">Verified</span>' : '<span class="status">Needs review</span>';
const filmCard = (film) => `<article class="card"><p class="eyebrow">${film.year ?? "Year unknown"}</p><h2><a href="/films/${film.id}/">${escape(film.title)}</a></h2><p>${escape(peopleMap.get(film.primaryDirector)?.name ?? "Credits being documented")}</p></article>`;
const personCard = (person) => `<article class="card person-card" data-filter-card data-name="${escape(person.name.toLowerCase())}" data-roles="${escape((person.roles ?? []).join("|").toLowerCase())}" data-letter="${escape(person.name.charAt(0).toUpperCase())}"><p class="eyebrow">${escape((person.roles ?? []).join(" · ") || "Film professional")}</p><h2><a href="/people/${person.id}/">${escape(person.name)}</a></h2>${person.professionalName ? `<p class="professional-name">Also known as ${escape(person.professionalName)}</p>` : ""}<p>${escape(person.biography.slice(0, 150))}${person.biography.length > 150 ? "…" : ""}</p>${person.archival ? '<span class="mini-status">Archival · unverified</span>' : ""}</article>`;
const organisationCard = (item) => `<article class="card" data-filter-card data-name="${escape(item.name.toLowerCase())}" data-roles="${escape(item.type.toLowerCase())}"><p class="eyebrow">${escape(item.type)}</p><h2><a href="/organisations/${item.id}/">${escape(item.name)}</a></h2><p>${escape(item.description.slice(0, 155))}${item.description.length > 155 ? "…" : ""}</p>${item.archival ? '<span class="mini-status">Archival · unverified</span>' : ""}</article>`;
const sourceList = (sources = []) => sources.length ? sources.map((source) => `<p>${source.url ? `<a href="${escape(source.url)}">${escape(source.note)}</a>` : escape(source.note)}</p>`).join("") : "<p>Sources still need to be added.</p>";

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(path.join(root, "public"), dist, { recursive: true });

write("", layout({ description: "Discover notable films and the people and organisations across Madagascar's film and audiovisual field.", body: `<section class="hero shell"><p class="kicker">Madagascar · Film · Audiovisual</p><h1>A living directory of Malagasy cinema.</h1><p class="lead">Discover notable films, filmmakers and the wider audiovisual field—then help document what is missing.</p><div class="actions"><a class="button primary" href="/people/">Explore people</a><a class="button" href="/films/">Browse films</a></div></section><section class="shell gateways" aria-label="Featured collections"><a class="gateway people-gateway" href="/people/"><p class="kicker">Directory</p><strong>People</strong><span>${people.length} filmmakers and audiovisual professionals →</span></a><a class="gateway films-gateway" href="/films/"><p class="kicker">Selected works</p><strong>Films</strong><span>${films.length} notable works and their connections →</span></a></section><section class="band"><div class="shell section"><div class="section-head"><div><p class="kicker">Selected works</p><h2>Films to know</h2></div><p>A starting selection—not a ranking or a finished canon.</p></div><div class="grid">${featuredFilms.map(filmCard).join("")}</div><p class="section-link"><a href="/films/">Explore all films →</a></p></div></section><section class="shell section"><div class="section-head"><div><p class="kicker">Featured profiles</p><h2>People shaping the field</h2></div><p>Established and contemporary voices, alongside a recovered professional directory awaiting community verification.</p></div><div class="grid">${featuredPeople.map(personCard).join("")}</div><p class="section-link"><a href="/people/">Explore all ${people.length} people →</a></p></section><section class="band"><div class="shell section directory-strip"><div><p class="kicker">The wider field</p><h2>People, organisations and connections</h2><p>Filmada's directory brings together professional roles, associations, institutions, companies and the works that connect them.</p></div><div class="metrics"><a href="/people/"><strong>${people.length}</strong><span>People</span></a><a href="/organisations/"><strong>${organisations.length}</strong><span>Archival organisations</span></a><a href="/directory/"><strong>A–Z</strong><span>Browse the directory</span></a></div></div></section><section class="shell callout"><p class="kicker">Built together</p><h2>Know something that should be here?</h2><p>Claim or correct a profile, document someone missing, add an organisation, or strengthen a record with a reliable source.</p><a class="button primary" href="/contribute/">How to contribute</a></section>` }));

write("directory", layout({ title: "Directory", current: "directory", description: "The people and organisations of Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Film and audiovisual field</p><h1>Directory</h1><p class="lead">Find people by profession and discover the organisations, associations and institutions around Malagasy cinema.</p></header><section class="shell directory-choices"><a href="/people/"><p class="kicker">${people.length} profiles</p><h2>People</h2><p>Directors, actors, screenwriters, producers, technicians and other audiovisual professionals.</p><span>Browse people →</span></a><a href="/organisations/"><p class="kicker">${organisations.length} starting records</p><h2>Organisations</h2><p>Associations, institutions, companies, festivals, schools, venues and collectives.</p><span>Browse organisations →</span></a></section><section class="shell archive-note"><h2>About the recovered directory</h2><p>${people.filter((person) => person.archival).length} profiles were safely recovered from Filmada's earlier community spreadsheet. Private addresses, phone numbers, email addresses, personal social accounts, equipment and software inventories have not been republished. Recovered professional details remain visibly marked until confirmed.</p></section>` }));

const alphabet = [...new Set(people.map((person) => person.name.charAt(0).toUpperCase()))];
write("people", layout({ title: "People", current: "people", description: "Notable filmmakers and people working across Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Directory · ${people.length} profiles</p><h1>People</h1><p class="lead">Notable filmmakers and a growing A–Z directory of audiovisual professionals connected to Madagascar.</p></header><section class="shell directory-tools" data-filter-root><div class="filter-bar"><label>Search people<input type="search" data-filter-search placeholder="Name, profession or keyword"></label><label>Profession<select data-filter-role><option value="">All professions</option>${roles.map((role) => `<option value="${escape(role.toLowerCase())}">${escape(role)}</option>`).join("")}</select></label></div><div class="alphabet" aria-label="Filter by first letter"><button type="button" data-filter-letter="" aria-pressed="true">All</button>${alphabet.map((letter) => `<button type="button" data-filter-letter="${letter}" aria-pressed="false">${letter}</button>`).join("")}</div><p class="result-count" aria-live="polite"><span data-result-count>${people.length}</span> profiles</p><div class="grid" data-filter-grid>${people.map(personCard).join("")}</div><p class="empty" data-filter-empty hidden>No profiles match those filters.</p></section>` }));

write("films", layout({ title: "Films", current: "films", description: "Selected and notable films connected to Madagascar.", body: `<header class="page shell"><p class="kicker">Selected works · ${films.length} records</p><h1>Films</h1><p class="lead">Notable Malagasy films and audiovisual works—their makers, contexts and connections. This is a growing selection, not a definitive canon.</p></header><section class="shell section"><div class="grid">${films.map(filmCard).join("")}</div></section>` }));

for (const person of people) {
  const linkedFilms = (person.films ?? []).map(({ id }) => filmsMap.get(id)).filter(Boolean);
  const details = [person.professionalName && ["Professional name", person.professionalName], person.originalRoleDescription && ["Original directory description", person.originalRoleDescription], person.organisation && ["Organisation listed in archive", person.organisation]].filter(Boolean);
  write(`people/${person.id}`, layout({ title: person.name, current: "people", description: person.biography.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/people/">← All people</a><p class="kicker">${escape((person.roles ?? []).join(" · "))}</p><h1>${escape(person.name)}</h1>${statusBadge(person)}${details.length ? `<dl class="facts">${details.map(([label, value]) => `<div><dt>${escape(label)}</dt><dd>${escape(value)}</dd></div>`).join("")}</dl>` : ""}<div class="prose"><p>${escape(person.biography)}</p>${person.professionalSummary ? `<p>${escape(person.professionalSummary)}</p>` : ""}</div>${person.selectedWork ? `<section class="profile-section"><h2>Selected work noted in the archive</h2><p>${escape(person.selectedWork)}</p></section>` : ""}${linkedFilms.length ? `<section><h2>Filmography in Filmada</h2><div class="grid">${linkedFilms.map(filmCard).join("")}</div></section>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(person.sources)}${person.archival ? '<p class="notice">This profile comes from Filmada’s earlier community directory. Contact details were deliberately excluded. Are you this person, or can you help verify the record? <a href="/contribute/">Suggest an update</a>.</p>' : '<p class="notice">This record still needs direct, structured citations.</p>'}</section></article>` }));
}

for (const film of films) {
  const director = peopleMap.get(film.primaryDirector);
  const relatedThemes = (film.themes ?? []).map((id) => themesMap.get(id)).filter(Boolean);
  const relatedPlaces = (film.places ?? []).map((id) => placesMap.get(id)).filter(Boolean);
  const relatedHistory = (film.history ?? []).map((id) => historyMap.get(id)).filter(Boolean);
  write(`films/${film.id}`, layout({ title: film.title, current: "films", description: film.synopsis.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/films/">← All films</a><p class="kicker">${film.year ?? "Year unknown"}${director ? ` · ${escape(director.name)}` : ""}</p><h1>${escape(film.title)}</h1>${film.alternativeTitle && film.alternativeTitle !== film.title ? `<p class="subtitle">${escape(film.alternativeTitle)}</p>` : ""}${statusBadge(film)}<div class="prose"><p>${escape(film.synopsis)}</p></div><dl class="facts">${director ? `<div><dt>Director</dt><dd><a href="/people/${director.id}/">${escape(director.name)}</a></dd></div>` : ""}${relatedPlaces.length ? `<div><dt>Places</dt><dd>${relatedPlaces.map((item) => escape(item.name)).join(", ")}</dd></div>` : ""}${relatedThemes.length ? `<div><dt>Themes</dt><dd>${relatedThemes.map((item) => escape(item.name)).join(", ")}</dd></div>` : ""}</dl>${relatedHistory.length ? `<section><h2>Historical context</h2>${relatedHistory.map((item) => `<article class="context"><p class="eyebrow">${escape(item.period ?? "Context")}</p><h3>${escape(item.title)}</h3><p>${escape(item.description)}</p></article>`).join("")}</section>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(film.sources)}<p class="notice">This record still needs direct, structured citations.</p></section></article>` }));
}

write("organisations", layout({ title: "Organisations", current: "directory", description: "Organisations across Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Directory · starting collection</p><h1>Organisations</h1><p class="lead">Associations, institutions, production companies, festivals, schools, cinemas, archives and collectives.</p></header><section class="shell section"><div class="grid">${organisations.map(organisationCard).join("")}</div><p class="notice directory-notice">These first records were recovered from the earlier Filmada Annuaire and require confirmation. <a href="/contribute/">Add or update an organisation</a>.</p></section>` }));
for (const item of organisations) write(`organisations/${item.id}`, layout({ title: item.name, current: "directory", description: item.description.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/organisations/">← All organisations</a><p class="kicker">${escape(item.type)}</p><h1>${escape(item.name)}</h1>${item.shortName ? `<p class="subtitle">${escape(item.shortName)}</p>` : ""}${statusBadge(item)}<div class="prose"><p>${escape(item.description)}</p></div>${item.activities?.length ? `<dl class="facts"><div><dt>Activities recorded</dt><dd>${item.activities.map(escape).join(" · ")}</dd></div></dl>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(item.sources)}<p class="notice">This archival organisation record needs current confirmation. <a href="/contribute/">Suggest an update</a>.</p></section></article>` }));

const genericStatus = '<span class="status">Needs review</span>';
write("history", layout({ title: "History of cinema in Madagascar", current: "history", description: "A developing timeline of film and audiovisual history in Madagascar.", body: `<header class="page shell"><p class="kicker">1900 to the present · work in progress</p><h1>History of cinema in Madagascar</h1><p class="lead">Films, filmmakers, screenings, cinemas, institutions, festivals and policies that have shaped Malagasy cinema and audiovisual culture.</p><p class="scope-note">This is a history of cinema—not a general history of Madagascar. Wider events appear only where they directly changed filmmaking, exhibition, preservation or the stories placed on screen.</p></header><section class="shell timeline">${history.map((item) => `<article><p class="eyebrow">${escape(item.period ?? "Date being documented")}</p><h2>${escape(item.title)}</h2>${genericStatus}<p>${escape(item.description)}</p>${item.sources?.length ? `<p class="timeline-source">${item.sources.map((source) => source.url ? `<a href="${escape(source.url)}">${escape(source.note)}</a>` : escape(source.note)).join(" · ")}</p>` : ""}</article>`).join("")}</section>` }));
write("opportunities", layout({ title: "Opportunities and resources", current: "opportunities", description: "Funding, support and festival resources for Madagascar's film community.", body: `<header class="page shell"><p class="kicker">Practical resources · maintained by Filmada</p><h1>Opportunities</h1><p class="lead">Funding and support accessible to Malagasy filmmakers, plus festivals to consider for films and projects connected to Madagascar.</p><p class="scope-note">These guides now live on Filmada. Programme status, eligibility and deadlines change: always confirm details on the organiser's official website before applying.</p></header><section class="shell resource-grid">${resources.map((item) => `<article class="resource-card"><p class="eyebrow">${escape(item.type)} · ${item.entries?.length ?? 0} starting entries</p><h2>${escape(item.title)}</h2><p>${escape(item.summary)}</p><p class="editorial-note">${escape(item.editorialNote)}</p><a href="/opportunities/${item.id}/">Read the Filmada guide →</a></article>`).join("")}</section><section class="shell callout compact-callout"><p class="kicker">Keep it useful</p><h2>Know a current fund, programme or festival?</h2><p>Help us add its official link, eligibility, next deadline and last-checked date.</p><a class="button primary" href="/contribute/">Share an opportunity</a></section>` }));
for (const resource of resources) write(`opportunities/${resource.id}`, layout({ title: resource.title, current: "opportunities", description: resource.summary, body: `<article class="detail shell resource-detail"><a class="back" href="/opportunities/">← All opportunity guides</a><p class="kicker">${escape(resource.type)} · recovered and maintained by Filmada</p><h1>${escape(resource.title)}</h1><p class="lead">${escape(resource.summary)}</p><p class="scope-note">${escape(resource.editorialNote)}</p><section class="guide-entries">${(resource.entries ?? []).map((entry) => `<article><p class="eyebrow">${escape(entry.region)}</p><h2>${escape(entry.name)}</h2><p>${escape(entry.description)}</p><h3>Who it may suit</h3><p>${escape(entry.eligibility)}</p><a href="${escape(entry.officialUrl)}">Check the official programme website →</a></article>`).join("")}</section><section class="notice"><h2>Help maintain this guide</h2><p>Filmada records useful starting points, not guarantees of eligibility or selection. If you find a changed rule, inactive programme or new opportunity, <a href="/contribute/">suggest an update</a>.</p></section></article>` }));
write("about", layout({ title: "About", description: "About Filmada, an open directory of Madagascar's film and audiovisual field.", body: `<article class="page shell narrow"><p class="kicker">About Filmada</p><h1>A shared map of Malagasy cinema</h1><div class="prose"><p>Filmada is an open, collaborative directory of Madagascar's film and audiovisual field.</p><p>It began through active members of the Horonan-tsary community, bringing together basic information about cinema history, people in the profession and current activity. The new Filmada preserves that community purpose while making the data safer, structured and openly maintainable.</p><p>People and films remain its most visible collections. Organisations, opportunities and history reveal the wider ecosystem around them.</p><p>Filmada is incomplete by design. It does not rank filmmakers or define a fixed canon; it grows through documented contributions, corrections and consent.</p></div></article>` }));
write("contribute", layout({ title: "Contribute", description: "Claim a profile or help document Madagascar's film and audiovisual field.", body: `<article class="page shell narrow"><p class="kicker">Open directory</p><h1>Help build Filmada</h1><p class="lead">You do not need technical knowledge. What matters is care, reliable information and commitment to Madagascar's film community.</p><div class="steps"><section><span>01</span><h2>Claim or correct a profile</h2><p>Tell us which record is yours, what should change and which contact details—if any—you explicitly want made public.</p></section><section><span>02</span><h2>Add what is missing</h2><p>Suggest a person, film, organisation or opportunity and include a reliable public source whenever possible.</p></section><section><span>03</span><h2>Join as an editor</h2><p>Committed contributors can maintain part of the directory through a simple editorial interface. Changes remain traceable and reviewable.</p></section></div><div class="privacy"><h2>Privacy comes first</h2><p>Filmada does not republish private addresses, old telephone numbers, personal email addresses, equipment inventories or personal social accounts from its archive. Contact information is published only when it is current, professional and intentionally shared for publication.</p></div><div class="actions"><a class="button primary" href="https://github.com/mosenjo/filmada/issues/new">Suggest an update on GitHub</a><a class="button" href="/admin/">Editor login</a></div><p class="notice">The editor interface is prepared, but its non-technical sign-in service still needs to be connected before invited editors can use it.</p></article>` }));

const notFound = layout({ title: "Page not found", description: "This Filmada page could not be found.", body: `<article class="page shell narrow"><p class="kicker">404</p><h1>Page not found</h1><p class="lead">This page may have moved as Filmada's directory evolves.</p><a class="button primary" href="/">Return to Filmada</a></article>` });
writeFileSync(path.join(dist, "404.html"), notFound);
const searchIndex = [...films.map((item) => ({ type: "Film", title: item.title, text: item.synopsis, url: `/films/${item.id}/` })), ...people.map((item) => ({ type: "Person", title: item.name, text: `${(item.roles ?? []).join(" ")} ${item.biography} ${item.professionalSummary ?? ""}`, url: `/people/${item.id}/` })), ...organisations.map((item) => ({ type: "Organisation", title: item.name, text: `${item.type} ${item.description}`, url: `/organisations/${item.id}/` })), ...history.map((item) => ({ type: "Cinema history", title: item.title, text: `${item.period ?? ""} ${item.description}`, url: "/history/" })), ...resources.flatMap((item) => [{ type: "Resource", title: item.title, text: item.summary, url: `/opportunities/${item.id}/` }, ...(item.entries ?? []).map((entry) => ({ type: "Opportunity resource", title: entry.name, text: `${entry.region} ${entry.description} ${entry.eligibility}`, url: `/opportunities/${item.id}/` }))])];
writeFileSync(path.join(dist, "search-index.json"), JSON.stringify(searchIndex));
writeFileSync(path.join(dist, ".nojekyll"), "");
console.log(`Built Filmada with ${people.length} people, ${films.length} films, ${organisations.length} organisations, ${history.length} cinema-history entries and ${resources.length} resource guides.`);
