import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");
const escape = (value = "") => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character]);
const readCollection = (name) => readdirSync(path.join(root, "data", name)).filter((file) => file.endsWith(".json")).map((file) => JSON.parse(readFileSync(path.join(root, "data", name, file), "utf8")));
const sortName = (a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" });
const films = readCollection("films").sort((a, b) => (b.year ?? 0) - (a.year ?? 0));
const people = readCollection("people").sort(sortName);
const organisations = readCollection("organisations").sort(sortName);
const places = readCollection("places").sort(sortName);
const themes = readCollection("themes").sort(sortName);
const history = readCollection("history").sort((a, b) => (a.year ?? 9999) - (b.year ?? 9999));
const resources = readCollection("resources").sort((a, b) => a.title.localeCompare(b.title, "en", { sensitivity: "base" }));
const byId = (items) => new Map(items.map((item) => [item.id, item]));
const peopleMap = byId(people), filmsMap = byId(films), placesMap = byId(places), themesMap = byId(themes), historyMap = byId(history);
const featuredFilmIds = ["tabataba", "mahaleo", "ady-gasy", "fahavalo-madagascar-1947", "disco-afrika", "malagasy-mankany"];
const featuredFilms = featuredFilmIds.map((id) => filmsMap.get(id)).filter(Boolean);
const featuredPeople = people.filter((person) => !person.archival).slice(0, 6);
const roles = [...new Set(people.flatMap((person) => person.roles ?? []))].sort();

function layout({ title, description, body, current = "" }) {
  const pageTitle = title ? `${escape(title)} — Filmada` : "Filmada — Malagasy film and audiovisual directory";
  const nav = (key, href, label, emphasis = false) => `<a class="${emphasis ? "nav-emphasis" : ""}" ${current === key ? 'aria-current="page"' : ""} href="${href}">${label}</a>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${pageTitle}</title><meta name="description" content="${escape(description)}"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip" href="#content">Skip to content</a><header class="site-header"><nav class="nav shell" aria-label="Main navigation"><a class="brand" href="/"><span></span>Filmada</a><button class="menu" aria-expanded="false" aria-controls="navlinks">Menu</button><div id="navlinks" class="navlinks">${nav("directory", "/directory/", "Directory")}${nav("people", "/people/", "People", true)}${nav("films", "/films/", "Films", true)}${nav("opportunities", "/opportunities/", "Opportunities")}${nav("history", "/history/", "History")}<a href="/contribute/">Contribute</a><span class="language-switch">{{LANGUAGE_SWITCH}}</span></div></nav></header><main id="content">${body}</main><footer><div class="shell footer"><div><a class="brand" href="/"><span></span>Filmada</a><p>An open, collaborative directory of Madagascar's film and audiovisual field—built carefully, one verified fragment at a time.</p></div><div><a href="/directory/">Directory</a><a href="/about/">About</a><a href="/contribute/">Contribute</a><a href="https://github.com/mosenjo/filmada">Source on GitHub</a></div></div></footer><script src="/site.js"></script></body></html>`;
}

function write(route, html) {
  const directory = path.join(dist, route);
  mkdirSync(directory, { recursive: true });
  writeFileSync(path.join(directory, "index.html"), html);
}

const statusBadge = (record) => record.archival ? '<span class="status archival">Archival record · needs confirmation</span>' : record.status === "verified" ? '<span class="status verified">Verified</span>' : '<span class="status">Needs review</span>';
const filmCard = (film) => `<article class="card"><p class="eyebrow">${film.year ?? "Year unknown"}</p><h2><a href="/films/${film.id}/">${escape(film.title)}</a></h2><p>${escape(peopleMap.get(film.primaryDirector)?.name ?? "Credits being documented")}</p></article>`;
const personCard = (person) => `<article class="card person-card" data-filter-card data-name="${escape(person.name.toLowerCase())}" data-roles="${escape((person.roles ?? []).join("|").toLowerCase())}" data-letter="${escape(person.name.charAt(0).toUpperCase())}"><p class="eyebrow">${escape((person.roles ?? []).join(" · ") || "Film professional")}</p><h2><a href="/people/${person.id}/">${escape(person.name)}</a></h2>${person.professionalName ? `<p class="professional-name">Also known as ${escape(person.professionalName)}</p>` : ""}<p>${escape(person.biography.slice(0, 150))}${person.biography.length > 150 ? "…" : ""}</p>${person.archival ? '<span class="mini-status">Archival · unverified</span>' : ""}</article>`;
const organisationCard = (item) => `<article class="card" data-filter-card data-name="${escape(item.name.toLowerCase())}" data-roles="${escape(item.type.toLowerCase())}"><p class="eyebrow">${escape(item.type)}</p><h2><a href="/organisations/${item.id}/">${escape(item.name)}</a></h2><p>${escape(item.description.slice(0, 155))}${item.description.length > 155 ? "…" : ""}</p>${item.archival ? '<span class="mini-status">Archival · unverified</span>' : ""}</article>`;
const sourceList = (sources = []) => sources.length ? sources.map((source) => `<p>${source.url ? `<a href="${escape(source.url)}">${escape(source.note)}</a>` : escape(source.note)}</p>`).join("") : "<p>Sources still need to be added.</p>";

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });
cpSync(path.join(root, "public"), dist, { recursive: true });

write("", layout({ description: "Discover notable films and the people and organisations across Madagascar's film and audiovisual field.", body: `<section class="hero shell"><p class="kicker">Madagascar · Film · Audiovisual</p><h1>A living directory of Malagasy cinema.</h1><p class="lead">Discover notable films, filmmakers and the wider audiovisual field—then help document what is missing.</p><div class="actions"><a class="button primary" href="/people/">Explore people</a><a class="button" href="/films/">Browse films</a></div></section><section class="shell gateways" aria-label="Featured collections"><a class="gateway people-gateway" href="/people/"><p class="kicker">Directory</p><strong>People</strong><span>${people.length} filmmakers and audiovisual professionals →</span></a><a class="gateway films-gateway" href="/films/"><p class="kicker">Selected works</p><strong>Films</strong><span>${films.length} notable works and their connections →</span></a></section><section class="band"><div class="shell section"><div class="section-head"><div><p class="kicker">Selected works</p><h2>Films to know</h2></div><p>A starting selection—not a ranking or a finished canon.</p></div><div class="grid">${featuredFilms.map(filmCard).join("")}</div><p class="section-link"><a href="/films/">Explore all films →</a></p></div></section><section class="shell section"><div class="section-head"><div><p class="kicker">Featured profiles</p><h2>People shaping the field</h2></div><p>Established and contemporary voices, alongside a recovered professional directory awaiting community verification.</p></div><div class="grid">${featuredPeople.map(personCard).join("")}</div><p class="section-link"><a href="/people/">Explore all ${people.length} people →</a></p></section><section class="band"><div class="shell section directory-strip"><div><p class="kicker">The wider field</p><h2>People, organisations and connections</h2><p>Filmada's directory brings together professional roles, associations, institutions, companies and the works that connect them.</p></div><div class="metrics"><a href="/people/"><strong>${people.length}</strong><span>People</span></a><a href="/organisations/"><strong>${organisations.length}</strong><span>Archival organisations</span></a><a href="/directory/"><strong>A–Z</strong><span>Browse the directory</span></a></div></div></section><section class="shell callout"><p class="kicker">Built together</p><h2>Know something that should be here?</h2><p>Claim or correct a profile, document someone missing, add an organisation, or strengthen a record with a reliable source.</p><a class="button primary" href="/contribute/">How to contribute</a></section>` }));

write("directory", layout({ title: "Directory", current: "directory", description: "The people and organisations of Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Film and audiovisual field</p><h1>Directory</h1><p class="lead">Find people by profession and discover the organisations, associations and institutions around Malagasy cinema.</p></header><section class="shell directory-choices"><a href="/people/"><p class="kicker">${people.length} profiles</p><h2>People</h2><p>Directors, actors, screenwriters, producers, technicians and other audiovisual professionals.</p><span>Browse people →</span></a><a href="/organisations/"><p class="kicker">${organisations.length} starting records</p><h2>Organisations</h2><p>Associations, institutions, companies, festivals, schools, venues and collectives.</p><span>Browse organisations →</span></a></section><section class="shell archive-note"><h2>About the recovered directory</h2><p>${people.filter((person) => person.archival).length} profiles were safely recovered from Filmada's earlier community spreadsheet. Private addresses, phone numbers, email addresses, personal social accounts, equipment and software inventories have not been republished. Recovered professional details remain visibly marked until confirmed.</p></section>` }));

const alphabet = [...new Set(people.map((person) => person.name.charAt(0).toUpperCase()))];
write("people", layout({ title: "People", current: "people", description: "Notable filmmakers and people working across Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Directory · ${people.length} profiles</p><h1>People</h1><p class="lead">Notable filmmakers and a growing A–Z directory of audiovisual professionals connected to Madagascar.</p></header><section class="shell directory-tools" data-filter-root><div class="filter-bar"><label>Search people<input type="search" data-filter-search placeholder="Name, profession or keyword"></label><label>Profession<select data-filter-role><option value="">All professions</option>${roles.map((role) => `<option value="${escape(role.toLowerCase())}">${escape(role)}</option>`).join("")}</select></label></div><div class="alphabet" aria-label="Filter by first letter"><button type="button" data-filter-letter="" aria-pressed="true">All</button>${alphabet.map((letter) => `<button type="button" data-filter-letter="${letter}" aria-pressed="false">${letter}</button>`).join("")}</div><p class="result-count" aria-live="polite"><span data-result-count>${people.length}</span> profiles</p><div class="grid" data-filter-grid>${people.map(personCard).join("")}</div><p class="empty" data-filter-empty hidden>No profiles match those filters.</p></section>` }));

write("films", layout({ title: "Films", current: "films", description: "Selected and notable films connected to Madagascar.", body: `<header class="page shell"><p class="kicker">Selected works · ${films.length} records</p><h1>Films</h1><p class="lead">Notable Malagasy films and audiovisual works—their makers, contexts and connections. This is a growing selection, not a definitive canon.</p></header><section class="shell section"><div class="grid">${films.map(filmCard).join("")}</div></section>` }));

for (const person of people) {
  const linkedFilms = (person.films ?? []).map(({ id }) => filmsMap.get(id)).filter(Boolean);
  const details = [person.professionalName && ["Professional name", person.professionalName], person.originalRoleDescription && ["Original directory description", person.originalRoleDescription], person.organisation && ["Organisation listed in archive", person.organisation]].filter(Boolean);
  write(`people/${person.id}`, layout({ title: person.name, current: "people", description: person.biography.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/people/">← All people</a><p class="kicker">${escape((person.roles ?? []).join(" · "))}</p><h1>${escape(person.name)}</h1>${statusBadge(person)}${details.length ? `<dl class="facts">${details.map(([label, value]) => `<div><dt>${escape(label)}</dt><dd>${escape(value)}</dd></div>`).join("")}</dl>` : ""}<div class="prose"><p>${escape(person.biography)}</p>${person.professionalSummary ? `<p>${escape(person.professionalSummary)}</p>` : ""}</div>${person.selectedWork ? `<section class="profile-section"><h2>Selected work noted in the archive</h2><p>${escape(person.selectedWork)}</p></section>` : ""}${linkedFilms.length ? `<section><h2>Filmography in Filmada</h2><div class="grid">${linkedFilms.map(filmCard).join("")}</div></section>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(person.sources)}${person.archival ? '<p class="notice">This profile comes from Filmada’s earlier community directory. Contact details were deliberately excluded. Are you this person, or can you help verify the record? <a href="/contribute/">Suggest an update</a>.</p>' : '<p class="notice">This record still needs direct, structured citations.</p>'}</section></article>` }));
}

for (const film of films) {
  const director = peopleMap.get(film.primaryDirector);
  const relatedThemes = (film.themes ?? []).map((id) => themesMap.get(id)).filter(Boolean);
  const relatedPlaces = (film.places ?? []).map((id) => placesMap.get(id)).filter(Boolean);
  const relatedHistory = (film.history ?? []).map((id) => historyMap.get(id)).filter(Boolean);
  write(`films/${film.id}`, layout({ title: film.title, current: "films", description: film.synopsis.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/films/">← All films</a><p class="kicker">${film.year ?? "Year unknown"}${director ? ` · ${escape(director.name)}` : ""}</p><h1>${escape(film.title)}</h1>${film.alternativeTitle && film.alternativeTitle !== film.title ? `<p class="subtitle">${escape(film.alternativeTitle)}</p>` : ""}${statusBadge(film)}<div class="prose"><p>${escape(film.synopsis)}</p></div><dl class="facts">${director ? `<div><dt>Director</dt><dd><a href="/people/${director.id}/">${escape(director.name)}</a></dd></div>` : ""}${relatedPlaces.length ? `<div><dt>Places</dt><dd>${relatedPlaces.map((item) => escape(item.name)).join(", ")}</dd></div>` : ""}${relatedThemes.length ? `<div><dt>Themes</dt><dd>${relatedThemes.map((item) => escape(item.name)).join(", ")}</dd></div>` : ""}</dl>${relatedHistory.length ? `<section><h2>Historical context</h2>${relatedHistory.map((item) => `<article class="context"><p class="eyebrow">${escape(item.period ?? "Context")}</p><h3>${escape(item.title)}</h3><p>${escape(item.description)}</p></article>`).join("")}</section>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(film.sources)}<p class="notice">This record still needs direct, structured citations.</p></section></article>` }));
}

write("organisations", layout({ title: "Organisations", current: "directory", description: "Organisations across Madagascar's film and audiovisual field.", body: `<header class="page shell"><p class="kicker">Directory · starting collection</p><h1>Organisations</h1><p class="lead">Associations, institutions, production companies, festivals, schools, cinemas, archives and collectives.</p></header><section class="shell section"><div class="grid">${organisations.map(organisationCard).join("")}</div><p class="notice directory-notice">These first records were recovered from the earlier Filmada Annuaire and require confirmation. <a href="/contribute/">Add or update an organisation</a>.</p></section>` }));
for (const item of organisations) write(`organisations/${item.id}`, layout({ title: item.name, current: "directory", description: item.description.slice(0, 155), body: `<article class="detail shell"><a class="back" href="/organisations/">← All organisations</a><p class="kicker">${escape(item.type)}</p><h1>${escape(item.name)}</h1>${item.shortName ? `<p class="subtitle">${escape(item.shortName)}</p>` : ""}${statusBadge(item)}<div class="prose"><p>${escape(item.description)}</p></div>${item.activities?.length ? `<dl class="facts"><div><dt>Activities recorded</dt><dd>${item.activities.map(escape).join(" · ")}</dd></div></dl>` : ""}<section class="sources"><h2>Sources and provenance</h2>${sourceList(item.sources)}<p class="notice">This archival organisation record needs current confirmation. <a href="/contribute/">Suggest an update</a>.</p></section></article>` }));

const genericStatus = '<span class="status">Needs review</span>';
write("history", layout({ title: "History of cinema in Madagascar", current: "history", description: "A developing timeline of film and audiovisual history in Madagascar.", body: `<header class="page shell"><p class="kicker">1900 to the present · work in progress</p><h1>History of cinema in Madagascar</h1><p class="lead">Films, filmmakers, screenings, cinemas, institutions, festivals and policies that have shaped Malagasy cinema and audiovisual culture.</p><p class="scope-note">This is a history of cinema—not a general history of Madagascar. Wider events appear only where they directly changed filmmaking, exhibition, preservation or the stories placed on screen.</p></header><section class="shell timeline">${history.map((item) => `<article><p class="eyebrow">${escape(item.period ?? "Date being documented")}</p><h2>${escape(item.title)}</h2>${genericStatus}<p>${escape(item.description)}</p>${item.sources?.length ? `<p class="timeline-source">${item.sources.map((source) => source.url ? `<a href="${escape(source.url)}">${escape(source.note)}</a>` : escape(source.note)).join(" · ")}</p>` : ""}</article>`).join("")}</section>` }));
write("opportunities", layout({ title: "Opportunities and resources", current: "opportunities", description: "Funding, support and festival resources for Madagascar's film community.", body: `<header class="page shell"><p class="kicker">Practical resources · maintained by Filmada</p><h1>Opportunities</h1><p class="lead">Funding and support accessible to Malagasy filmmakers, plus festivals to consider for films and projects connected to Madagascar.</p><p class="scope-note">These guides now live on Filmada. Programme status, eligibility and deadlines change: always confirm details on the organiser's official website before applying.</p></header><section class="shell resource-grid">${resources.map((item) => `<article class="resource-card"><p class="eyebrow">${escape(item.type)} · ${item.entries?.length ?? 0} starting entries</p><h2>${escape(item.title)}</h2><p>${escape(item.summary)}</p><p class="editorial-note">${escape(item.editorialNote)}</p><a href="/opportunities/${item.id}/">Read the Filmada guide →</a></article>`).join("")}</section><section class="shell callout compact-callout"><p class="kicker">Keep it useful</p><h2>Know a current fund, programme or festival?</h2><p>Help us add its official link, eligibility, next deadline and last-checked date.</p><a class="button primary" href="/contribute/">Share an opportunity</a></section>` }));
for (const resource of resources) write(`opportunities/${resource.id}`, layout({ title: resource.title, current: "opportunities", description: resource.summary, body: `<article class="detail shell resource-detail"><a class="back" href="/opportunities/">← All opportunity guides</a><p class="kicker">${escape(resource.type)} · recovered and maintained by Filmada</p><h1>${escape(resource.title)}</h1><p class="lead">${escape(resource.summary)}</p><p class="scope-note">${escape(resource.editorialNote)}</p><section class="guide-entries">${(resource.entries ?? []).map((entry) => `<article><p class="eyebrow">${escape(entry.region)}</p><h2>${escape(entry.name)}</h2><p>${escape(entry.description)}</p><h3>Who it may suit</h3><p>${escape(entry.eligibility)}</p><a href="${escape(entry.officialUrl)}">Check the official programme website →</a></article>`).join("")}</section><section class="notice"><h2>Help maintain this guide</h2><p>Filmada records useful starting points, not guarantees of eligibility or selection. If you find a changed rule, inactive programme or new opportunity, <a href="/contribute/">suggest an update</a>.</p></section></article>` }));
write("about", layout({ title: "About", description: "About Filmada, an open directory of Madagascar's film and audiovisual field.", body: `<article class="page shell narrow"><p class="kicker">About Filmada</p><h1>A shared map of Malagasy cinema</h1><div class="prose"><p>Filmada is an open, collaborative directory of Madagascar's film and audiovisual field.</p><p>It began through active members of the Horonan-tsary community, bringing together basic information about cinema history, people in the profession and current activity. The new Filmada preserves that community purpose while making the data safer, structured and openly maintainable.</p><p>People and films remain its most visible collections. Organisations, opportunities and history reveal the wider ecosystem around them.</p><p>Filmada is incomplete by design. It does not rank filmmakers or define a fixed canon; it grows through documented contributions, corrections and consent.</p></div></article>` }));
write("contribute", layout({ title: "Contribute", description: "Claim a profile or help document Madagascar's film and audiovisual field.", body: `<article class="page shell contribution-page"><p class="kicker">Open directory</p><h1>Contribute to Filmada</h1><p class="lead">Suggest a person, film, organisation, opportunity or correction. Every contribution is reviewed before publication.</p><form class="contribution-form" data-contribution-form data-language="en"><div class="form-grid"><label>What would you like to contribute?<select name="type" required><option value="">Choose one</option><option>Person or professional profile</option><option>Film or audiovisual work</option><option>Organisation</option><option>Funding, festival or opportunity</option><option>Cinema-history correction</option><option>Other</option></select></label><label>Name or title<input name="subject" required placeholder="Person, film, organisation or subject"></label></div><label>What should Filmada add or change?<textarea name="details" required rows="8" placeholder="Give enough context for an editor to understand and verify the contribution."></textarea></label><label>Public sources<textarea name="sources" rows="4" placeholder="Paste one or more reliable public links, one per line."></textarea></label><label class="consent"><input type="checkbox" name="consent" required> I understand that my submission and its sources will be public on GitHub. I have not included a private address, telephone number or personal email address.</label><button class="button primary" type="submit">Prepare contribution</button><p class="form-help">The next step opens a prepared GitHub submission for your review. A free GitHub account is currently required. Nothing is published automatically.</p><p class="form-error" data-form-error hidden>Please complete the required fields.</p></form><aside class="privacy"><h2>Privacy and moderation</h2><p>Do not submit private contact information without the person's explicit consent. Filmada editors verify contributions, sources and consent before changing the directory.</p><p>Regular contributors may later be invited to use the <a href="/admin/">editor interface</a>.</p></aside></article>` }));

const notFound = layout({ title: "Page not found", description: "This Filmada page could not be found.", body: `<article class="page shell narrow"><p class="kicker">404</p><h1>Page not found</h1><p class="lead">This page may have moved as Filmada's directory evolves.</p><a class="button primary" href="/">Return to Filmada</a></article>` });
writeFileSync(path.join(dist, "404.html"), notFound);

const frenchReplacements = [
  ["Skip to content", "Aller au contenu"], ["Main navigation", "Navigation principale"],
  [">Directory<", ">Annuaire<"], [">People<", ">Personnes<"], [">Opportunities<", ">Opportunités<"], [">History<", ">Histoire<"], [">Contribute<", ">Contribuer<"], [">About<", ">À propos<"], [">Source on GitHub<", ">Code source sur GitHub<"],
  ["An open, collaborative directory of Madagascar's film and audiovisual field—built carefully, one verified fragment at a time.", "Un annuaire ouvert et collaboratif du cinéma et de l’audiovisuel à Madagascar — construit avec soin, une information vérifiée à la fois."],
  ["A living directory of Malagasy cinema.", "Un annuaire vivant du cinéma malgache."], ["Discover notable films, filmmakers and the wider audiovisual field—then help document what is missing.", "Découvrez des films, des cinéastes et l’ensemble du secteur audiovisuel — puis aidez-nous à documenter ce qui manque."],
  ["Explore people", "Explorer les personnes"], ["Browse films", "Parcourir les films"], ["Selected works", "Œuvres sélectionnées"], ["Films to know", "Films à connaître"], ["A starting selection—not a ranking or a finished canon.", "Une sélection de départ — ni classement, ni canon définitif."], ["Featured profiles", "Profils à découvrir"], ["People shaping the field", "Personnes qui font vivre le secteur"], ["Built together", "Construit ensemble"], ["Know something that should be here?", "Une information devrait figurer ici ?"], ["How to contribute", "Comment contribuer"],
  [`${people.length} filmmakers and audiovisual professionals`, `${people.length} cinéastes et professionnel·les de l’audiovisuel`], [`${films.length} notable works and their connections`, `${films.length} œuvres remarquables et leurs liens`], ["Explore all films", "Explorer tous les films"], [`Explore all ${people.length} people`, `Explorer les ${people.length} personnes`], ["Established and contemporary voices, alongside a recovered professional directory awaiting community verification.", "Des figures établies et contemporaines, aux côtés d’un annuaire professionnel récupéré qui attend la vérification de la communauté."], ["The wider field", "L’écosystème"], ["People, organisations and connections", "Personnes, organisations et liens"], ["Filmada's directory brings together professional roles, associations, institutions, companies and the works that connect them.", "L’annuaire Filmada réunit métiers, associations, institutions, entreprises et œuvres qui les relient."], ["Archival organisations", "Organisations d’archive"], ["Browse the directory", "Parcourir l’annuaire"], ["Claim or correct a profile, document someone missing, add an organisation, or strengthen a record with a reliable source.", "Réclamez ou corrigez un profil, documentez une personne absente, ajoutez une organisation ou renforcez une notice avec une source fiable."],
  ["Film and audiovisual field", "Cinéma et audiovisuel"], ["Find people by profession and discover the organisations, associations and institutions around Malagasy cinema.", "Trouvez des personnes par métier et découvrez les organisations, associations et institutions du cinéma malgache."], ["Browse people", "Parcourir les personnes"], ["About the recovered directory", "À propos de l’annuaire récupéré"],
  ["Search people", "Rechercher une personne"], ["Name, profession or keyword", "Nom, métier ou mot-clé"], [">Profession<select", ">Métier<select"], ["All professions", "Tous les métiers"], [">All<", ">Tous<"], ["No profiles match those filters.", "Aucun profil ne correspond à ces filtres."],
  ["Selected works ·", "Œuvres sélectionnées ·"], ["Notable Malagasy films and audiovisual works—their makers, contexts and connections. This is a growing selection, not a definitive canon.", "Films et œuvres audiovisuelles malgaches remarquables — leurs créateurs, contextes et liens. Cette sélection évolue et ne constitue pas un canon définitif."],
  ["Archival record · needs confirmation", "Notice d’archive · à confirmer"], ["Needs review", "À vérifier"], ["Verified", "Vérifié"], ["Year unknown", "Année inconnue"], ["Credits being documented", "Générique en cours de documentation"], ["Also known as", "Aussi connu·e sous le nom"], ["Archival · unverified", "Archive · non vérifiée"],
  ["← All people", "← Toutes les personnes"], ["Professional name", "Nom professionnel"], ["Original directory description", "Description dans l’ancien annuaire"], ["Organisation listed in archive", "Organisation indiquée dans l’archive"], ["Selected work noted in the archive", "Œuvre mentionnée dans l’archive"], ["Filmography in Filmada", "Filmographie dans Filmada"], ["Sources and provenance", "Sources et provenance"], ["Suggest an update", "Proposer une modification"],
  ["← All films", "← Tous les films"], ["Places", "Lieux"], ["Themes", "Thèmes"], ["Historical context", "Contexte historique"],
  ["History of cinema in Madagascar", "Histoire du cinéma à Madagascar"], ["1900 to the present · work in progress", "De 1900 à nos jours · travail en cours"], ["Films, filmmakers, screenings, cinemas, institutions, festivals and policies that have shaped Malagasy cinema and audiovisual culture.", "Films, cinéastes, projections, salles, institutions, festivals et politiques qui ont façonné le cinéma et la culture audiovisuelle malgaches."], ["This is a history of cinema—not a general history of Madagascar. Wider events appear only where they directly changed filmmaking, exhibition, preservation or the stories placed on screen.", "Il s’agit de l’histoire du cinéma, et non d’une histoire générale de Madagascar. Les événements nationaux n’apparaissent que lorsqu’ils ont directement influencé la création, la diffusion, la conservation ou les récits portés à l’écran."],
  ["Opportunities and resources", "Opportunités et ressources"], ["Practical resources · maintained by Filmada", "Ressources pratiques · maintenues par Filmada"], ["Funding and support accessible to Malagasy filmmakers, plus festivals to consider for films and projects connected to Madagascar.", "Financements et soutiens accessibles aux cinéastes malgaches, ainsi que festivals à considérer pour les films et projets liés à Madagascar."], ["These guides now live on Filmada. Programme status, eligibility and deadlines change: always confirm details on the organiser's official website before applying.", "Ces guides sont désormais hébergés par Filmada. Les programmes, critères et échéances évoluent : vérifiez toujours les informations sur le site officiel avant de candidater."], ["Read the Filmada guide", "Lire le guide Filmada"], ["Keep it useful", "Gardons ces informations utiles"], ["Know a current fund, programme or festival?", "Vous connaissez un fonds, un programme ou un festival actif ?"], ["Share an opportunity", "Partager une opportunité"],
  ["Funding and support accessible to Malagasy filmmakers", "Fonds et soutiens accessibles aux cinéastes malgaches"], ["Festivals to consider for Malagasy filmmakers and producers", "Festivals à considérer pour les cinéastes et producteurs malgaches"], ["← All opportunity guides", "← Tous les guides d’opportunités"], ["recovered and maintained by Filmada", "récupéré et maintenu par Filmada"], ["Who it may suit", "À qui cela peut convenir"], ["Check the official programme website", "Consulter le site officiel du programme"], ["Help maintain this guide", "Aidez à maintenir ce guide"],
  ["Open directory", "Annuaire ouvert"], ["Contribute to Filmada", "Contribuer à Filmada"], ["Suggest a person, film, organisation, opportunity or correction. Every contribution is reviewed before publication.", "Proposez une personne, un film, une organisation, une opportunité ou une correction. Chaque contribution est vérifiée avant publication."], ["What would you like to contribute?", "Que souhaitez-vous proposer ?"], ["Choose one", "Choisir"], ["Person or professional profile", "Personne ou profil professionnel"], ["Film or audiovisual work", "Film ou œuvre audiovisuelle"], ["Funding, festival or opportunity", "Financement, festival ou opportunité"], ["Cinema-history correction", "Correction sur l’histoire du cinéma"], [">Other</option>", ">Autre</option>"], ["Name or title", "Nom ou titre"], ["Person, film, organisation or subject", "Personne, film, organisation ou sujet"], ["What should Filmada add or change?", "Que doit ajouter ou modifier Filmada ?"], ["Give enough context for an editor to understand and verify the contribution.", "Donnez assez de contexte pour permettre la compréhension et la vérification."], ["Public sources", "Sources publiques"], ["Paste one or more reliable public links, one per line.", "Collez un ou plusieurs liens publics fiables, un par ligne."], ["I understand that my submission and its sources will be public on GitHub. I have not included a private address, telephone number or personal email address.", "Je comprends que ma contribution et ses sources seront publiques sur GitHub. Je n’ai inclus ni adresse privée, ni numéro de téléphone, ni adresse courriel personnelle."], ["Prepare contribution", "Préparer la contribution"], ["The next step opens a prepared GitHub submission for your review. A free GitHub account is currently required. Nothing is published automatically.", "L’étape suivante ouvre une contribution GitHub préremplie pour votre vérification. Un compte GitHub gratuit est actuellement nécessaire. Rien n’est publié automatiquement."], ["Please complete the required fields.", "Veuillez remplir les champs obligatoires."], ["Privacy and moderation", "Vie privée et modération"], ["Do not submit private contact information without the person's explicit consent. Filmada editors verify contributions, sources and consent before changing the directory.", "Ne transmettez aucune coordonnée privée sans le consentement explicite de la personne. Les éditeurs de Filmada vérifient les contributions, les sources et le consentement avant toute modification."], ["Regular contributors may later be invited to use the", "Les contributeurs réguliers pourront ensuite être invités à utiliser l’"], ["editor interface", "interface d’édition"],
  ["Page not found", "Page introuvable"], ["This page may have moved as Filmada's directory evolves.", "Cette page a peut-être été déplacée au fil de l’évolution de Filmada."], ["Return to Filmada", "Retourner à Filmada"]
];
const replaceAll = (text, from, to) => text.split(from).join(to);
const toFrench = (html, relativeRoute) => {
  let translated = html.replace('<html lang="en">', '<html lang="fr">');
  for (const [from, to] of frenchReplacements) translated = replaceAll(translated, from, to);
  const roleTranslations = [[/\bAssistant Director\b/g, "Assistant·e à la réalisation"], [/\bDirector\b/g, "Réalisation"], [/\bScreenwriter\b/g, "Scénario"], [/\bActor\b/g, "Interprétation"], [/\bProducer\b/g, "Production"], [/\bEditing\b/g, "Montage"], [/\bSound\b/g, "Son"], [/\bPhotography\b/g, "Photographie"], [/\bTraining\b/g, "Formation"], [/\bOther audiovisual profession\b/g, "Autre métier de l’audiovisuel"], [/\bRole being documented\b/g, "Métier en cours de documentation"]];
  for (const [pattern, replacement] of roleTranslations) translated = translated.replace(pattern, replacement);
  if (relativeRoute.startsWith("people/") || relativeRoute.startsWith("films/") || relativeRoute.startsWith("organisations/")) translated = translated.replace('<div class="prose">', '<p class="translation-note">Certaines notices récupérées sont encore disponibles uniquement dans leur langue d’origine. La traduction française est progressive.</p><div class="prose">');
  return translated;
};
const htmlFiles = [];
const findHtml = (directory, prefix = "") => {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory() && entry.name !== "admin" && entry.name !== "en") findHtml(path.join(directory, entry.name), relative);
    else if (entry.isFile() && entry.name.endsWith(".html")) htmlFiles.push(relative);
  }
};
findHtml(dist);
for (const relativeFile of htmlFiles) {
  const source = readFileSync(path.join(dist, relativeFile), "utf8");
  const relativeRoute = relativeFile === "index.html" ? "" : relativeFile.replace(/index\.html$/, "");
  const frenchRoute = `/${relativeRoute}`;
  const englishRoute = `/en/${relativeRoute}`;
  const alternates = `<link rel="alternate" hreflang="fr" href="https://filmada.org${frenchRoute}"><link rel="alternate" hreflang="en" href="https://filmada.org${englishRoute}">`;
  const english = source.replace("</head>", `${alternates}</head>`).replace(/href="\/(?!styles\.css|admin\/|en\/)([^"]*)"/g, 'href="/en/$1"').replace("{{LANGUAGE_SWITCH}}", `<a href="${frenchRoute}">FR</a><a aria-current="page" href="${englishRoute}">EN</a>`);
  const englishTarget = path.join(dist, "en", relativeFile);
  mkdirSync(path.dirname(englishTarget), { recursive: true });
  writeFileSync(englishTarget, english);
  const french = toFrench(source, relativeRoute).replace("</head>", `${alternates}</head>`).replace("{{LANGUAGE_SWITCH}}", `<a aria-current="page" href="${frenchRoute}">FR</a><a href="${englishRoute}">EN</a>`);
  writeFileSync(path.join(dist, relativeFile), french);
}
const searchIndex = [...films.map((item) => ({ type: "Film", title: item.title, text: item.synopsis, url: `/films/${item.id}/` })), ...people.map((item) => ({ type: "Person", title: item.name, text: `${(item.roles ?? []).join(" ")} ${item.biography} ${item.professionalSummary ?? ""}`, url: `/people/${item.id}/` })), ...organisations.map((item) => ({ type: "Organisation", title: item.name, text: `${item.type} ${item.description}`, url: `/organisations/${item.id}/` })), ...history.map((item) => ({ type: "Cinema history", title: item.title, text: `${item.period ?? ""} ${item.description}`, url: "/history/" })), ...resources.flatMap((item) => [{ type: "Resource", title: item.title, text: item.summary, url: `/opportunities/${item.id}/` }, ...(item.entries ?? []).map((entry) => ({ type: "Opportunity resource", title: entry.name, text: `${entry.region} ${entry.description} ${entry.eligibility}`, url: `/opportunities/${item.id}/` }))])];
writeFileSync(path.join(dist, "search-index.json"), JSON.stringify(searchIndex));
writeFileSync(path.join(dist, ".nojekyll"), "");
console.log(`Built Filmada with ${people.length} people, ${films.length} films, ${organisations.length} organisations, ${history.length} cinema-history entries and ${resources.length} resource guides.`);
